画像を表示するように修正
Yadosai/official_site2024new pull request #51
Opened 2024-04-21 02:51 UTC by nowex35

2024-04-21 10:09 UTC, tarou-jp requested changes

2024-04-21 10:09 UTC, tarou-jp commented on front/components/thanks/index.vue
> +import Seirokuya from '~/assets/img/sponsor/seirokuya.png'
これ、import分コンポーネント側で書けないんですか？
ここに書くくらいなら、staticディレクトリに入れたい

2024-04-21 10:09 UTC, tarou-jp commented on front/components/thanks/sponsorItem.vue
> +    white-space: pre-wrap; /* 改行と空白を保持 */
fontとかのもろもろがないですが、figmaのcssつかってますか？

2024-04-21 10:09 UTC, tarou-jp commented on front/components/thanks/sponsorItem.vue
> +    height: 70px; /* コンテナの高さも親要素に合わせて100%に設定 */
縦に中央揃えにするcssがないです

2024-04-21 10:09 UTC, tarou-jp commented on front/components/thanks/sponsorItem.vue
> +    height: 160px; /* 高さを160pxに設定 */
コメントアウト不要なので、消してほしい。

2024-04-21 10:10 UTC, tarou-jp commented on front/components/thanks/index.vue
> +import Seirokuya from '~/assets/img/sponsor/seirokuya.png'
画像のimport文のことです

2024-04-21 10:27 UTC, nowex35 commented on front/components/thanks/index.vue
> +import Seirokuya from '~/assets/img/sponsor/seirokuya.png'
コンポーネント側で書くと（コンポーネントにデータをあたえるとしたら）そもそもコンポーネントではなくなってしまうのではないでしょうか？
何らかの条件文で呼び出すようにはできるかもしれないですが。コンポーネント側にimportを記述しても呼び出せませんでした。

2024-04-21 11:22 UTC, tarou-jp commented on front/components/thanks/index.vue
> +import Seirokuya from '~/assets/img/sponsor/seirokuya.png'
なるほど、ならpublicに入れて使ってください

2024-04-29 08:17 UTC, tarou-jp approved these changes

2024-04-29 08:17 UTC, tarou-jp commented on front/components/thanks/index.vue
> +    <sponsorItem sponsorUrl="https://www.seirock-ya.jp/" :sponsorLogoUrl="SeirokuyaImg" :sponsorDescript="SeirokuyaText"  />
<sponsorItem sponsorUrl="https://www.seirock-ya.jp/" sponsorLogoUrl="img/thanks/seirokuya.png"
        :sponsorDescript="SeirokuyaText" />
        
       publicに入れれば上で使えます。

2024-04-29 08:17 UTC, merged